# [DinosGym]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [DinosGym]    Script Date: 14/7/2023 11:38:06 ******/
CREATE DATABASE [DinosGym]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DinosGym', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DinosGym.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DinosGym_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DinosGym_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DinosGym] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DinosGym].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DinosGym] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DinosGym] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DinosGym] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DinosGym] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DinosGym] SET ARITHABORT OFF 
GO
ALTER DATABASE [DinosGym] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DinosGym] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DinosGym] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DinosGym] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DinosGym] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DinosGym] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DinosGym] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DinosGym] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DinosGym] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DinosGym] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DinosGym] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DinosGym] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DinosGym] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DinosGym] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DinosGym] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DinosGym] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DinosGym] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DinosGym] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DinosGym] SET  MULTI_USER 
GO
ALTER DATABASE [DinosGym] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DinosGym] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DinosGym] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DinosGym] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DinosGym] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DinosGym] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DinosGym] SET QUERY_STORE = ON
GO
ALTER DATABASE [DinosGym] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Admin]

In [0]:
USE [DinosGym]
GO

In [0]:
/****** Object:  Table [dbo].[Admin]    Script Date: 14/7/2023 11:38:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[id] [int] NOT NULL,
	[Nombre] [varchar](300) NULL,
	[Password] [varchar](300) NULL,
	[admin] [bit] NULL
) ON [PRIMARY]
GO

# [dbo].[Compra]

In [0]:
/****** Object:  Table [dbo].[Compra]    Script Date: 14/7/2023 11:38:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Compra](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[Precio] [money] NULL,
	[IdUsuario] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Membresia]

In [0]:
/****** Object:  Table [dbo].[Membresia]    Script Date: 14/7/2023 11:38:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Membresia](
	[FechaDeInicio] [date] NULL,
	[FechaDeFin] [date] NULL,
	[IdTipoMembresia] [int] NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
	[IdUsuarios] [int] NULL,
	[Activo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TipoMembresia]

In [0]:
/****** Object:  Table [dbo].[TipoMembresia]    Script Date: 14/7/2023 11:38:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoMembresia](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](300) NULL,
	[precio] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Usuarios]

In [0]:
/****** Object:  Table [dbo].[Usuarios]    Script Date: 14/7/2023 11:38:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Altura] [decimal](10, 2) NULL,
	[Nombre] [varchar](50) NULL,
	[Apellido] [varchar](50) NULL,
	[Documento] [bigint] NULL,
	[FechaDeNacimiento] [smalldatetime] NULL,
	[Pago] [bit] NULL,
	[Peso] [int] NULL,
	[Contacto] [bigint] NULL,
	[FotoDePerfil] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Admin]

In [0]:
INSERT [dbo].[Admin] ([id], [Nombre], [Password], [admin]) VALUES (1, N'carlos', N'123', 1)
GO

# [dbo].[Membresia]

In [0]:
SET IDENTITY_INSERT [dbo].[Membresia] ON 
INSERT [dbo].[Membresia] ([FechaDeInicio], [FechaDeFin], [IdTipoMembresia], [id], [IdUsuarios], [Activo]) VALUES (CAST(N'2023-07-01' AS Date), CAST(N'2023-08-01' AS Date), 1, 22, 0, 0)
INSERT [dbo].[Membresia] ([FechaDeInicio], [FechaDeFin], [IdTipoMembresia], [id], [IdUsuarios], [Activo]) VALUES (CAST(N'2023-07-01' AS Date), CAST(N'2023-08-01' AS Date), 1, 23, 0, 0)
INSERT [dbo].[Membresia] ([FechaDeInicio], [FechaDeFin], [IdTipoMembresia], [id], [IdUsuarios], [Activo]) VALUES (CAST(N'2023-07-01' AS Date), CAST(N'2023-08-01' AS Date), 1, 24, 26, 1)
INSERT [dbo].[Membresia] ([FechaDeInicio], [FechaDeFin], [IdTipoMembresia], [id], [IdUsuarios], [Activo]) VALUES (CAST(N'2023-07-12' AS Date), CAST(N'2023-08-12' AS Date), 1, 25, 26, 1)
INSERT [dbo].[Membresia] ([FechaDeInicio], [FechaDeFin], [IdTipoMembresia], [id], [IdUsuarios], [Activo]) VALUES (CAST(N'2023-07-12' AS Date), CAST(N'2023-08-12' AS Date), 1, 32, 32, 1)
SET IDENTITY_INSERT [dbo].[Membresia] OFF
GO

# [dbo].[TipoMembresia]

In [0]:
SET IDENTITY_INSERT [dbo].[TipoMembresia] ON 
INSERT [dbo].[TipoMembresia] ([id], [nombre], [precio]) VALUES (1, N'Pase Libre', 3000.0000)
INSERT [dbo].[TipoMembresia] ([id], [nombre], [precio]) VALUES (2, N'Funcional', 4500.0000)
SET IDENTITY_INSERT [dbo].[TipoMembresia] OFF
GO

# [dbo].[Usuarios]

In [0]:
SET IDENTITY_INSERT [dbo].[Usuarios] ON 
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (26, CAST(1.88 AS Decimal(10, 2)), N'ca', N'testdepase', 34333222, CAST(N'2023-06-30T17:22:00' AS SmallDateTime), 0, 88, 123123122, N'')
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (27, CAST(1.40 AS Decimal(10, 2)), N'testdeprueba', N'demsj', 41837927, CAST(N'2023-07-05T21:10:00' AS SmallDateTime), 0, 88, 1144345687, N'')
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (28, CAST(0.99 AS Decimal(10, 2)), N'prueba', N'test', 45333222, CAST(N'2023-07-06T13:37:00' AS SmallDateTime), 0, 10, 3399887766, N'')
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (29, CAST(199.00 AS Decimal(10, 2)), N'test', N'deactivo', 32444555, CAST(N'2023-07-13T14:28:00' AS SmallDateTime), 0, 100, 4433225566, N'')
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (30, CAST(1.99 AS Decimal(10, 2)), N'prueba', N'detodo', 45678876, CAST(N'2023-07-12T11:47:00' AS SmallDateTime), 0, 100, 4455667788, N'')
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (32, CAST(1.88 AS Decimal(10, 2)), N'carlitos', N'testdepasefinal', 34333222, CAST(N'2023-06-30T17:22:00' AS SmallDateTime), 0, 89, 123123122, N'')
INSERT [dbo].[Usuarios] ([Id], [Altura], [Nombre], [Apellido], [Documento], [FechaDeNacimiento], [Pago], [Peso], [Contacto], [FotoDePerfil]) VALUES (34, CAST(1.88 AS Decimal(10, 2)), N'test', N'final', 0, CAST(N'2023-07-13T14:33:00' AS SmallDateTime), 1, 88, 8877445566, N'')
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
GO

# [DF__Membresia__Activ__03F0984C]

In [0]:
ALTER TABLE [dbo].[Membresia] ADD  DEFAULT ((0)) FOR [Activo]
GO

# [FK__Compra__IdUsuari__6A30C649]

In [0]:
ALTER TABLE [dbo].[Compra]  WITH CHECK ADD FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuarios] ([Id])
GO

# [DinosGym]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [DinosGym] SET  READ_WRITE 
GO